# GitHub Pages Configuration
# This file ensures that GitHub Pages knows this is a static site

# Specify the base path if deploying to a project site (username.github.io/repo-name)
baseurl: "/Predictive-Modeling-for-Smartphone-Purchase-Behavior-ML"

# Specify the build settings
markdown: kramdown

# Include the Dashboard folder
include:
  - "Dashboard"

# Disable Jekyll processing
github:
  is_project_page: true
  is_user_page: false
