# Netlify configuration file
[build]
  # Directory with the static files
  publish = "Dashboard"
  # No build command - just serve static files
  command = ""
  # Skip all dependency detection and installation
  ignore_dependencies = true
  
# Skip ALL dependency installation entirely
[build.environment]
  # Disable all package managers
  NETLIFY_USE_YARN = "false"
  NETLIFY_USE_NPM = "false"
  NETLIFY_USE_PNPM = "false"
  NETLIFY_USE_YARN_INSTALL = "false"
  NETLIFY_USE_PACKAGER = "false"
  NODE_VERSION = "none"
  PYTHON_VERSION = "off"
  RUBY_VERSION = "off"
  PHP_VERSION = "off"
  HUGO_VERSION = "off"
  JAVA_VERSION = "off"

# Redirects for SPA (Single Page Application)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Headers for security and caching
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "no-referrer-when-downgrade"
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline' https://cdn.jsdelivr.net; style-src 'self' 'unsafe-inline' https://cdn.jsdelivr.net; img-src 'self' data:; font-src 'self' https://cdn.jsdelivr.net;"
